// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Data.Configurations
{
    public partial class UserLoginConfiguration : IEntityTypeConfiguration<UserLogin>
    {
        public void Configure(EntityTypeBuilder<UserLogin> entity)
        {
            entity
            .HasNoKey()
            .ToTable("user_login", "usr");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.FirstName)
            .IsRequired()
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.LastName)
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.UserId).ValueGeneratedOnAdd();
            entity.Property(e => e.UserRole)
            .HasMaxLength(250)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserLogin> entity);
    }
}
